# This is a sample aws-auth-patch.yml file. 
# Actual aws-auth-patch.yml will be created at /System/Volumes/Data/private/tmp/aws-auth-patch.yml path.

apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::650880261103:role/eksctl-eksctl-demo-nodegroup-ng-b-NodeInstanceRole-1UHI6ILRC4J9T
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::650880261103:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-30T13:46:11Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1810"
  uid: 9e2c3f94-36e1-4bd3-99e6-2cc7cc779957
